id = "crates-autocomplete"
name = "Crates Autocomplete"
description = "Provides intelligent autocomplete, versioning, and features for Rust crates in Cargo.toml files using crates-lsp"
version = "0.1.2"
schema_version = 1
authors = ["Radu <radu0071@gmail.com>"]
repository = "https://github.com/countradooku/crates-autocomplete"

[language_servers.crates-lsp]
name = "crates-lsp"
language = "TOML"

[[commands]]
name = "crates-zed.open_documentation"
title = "Crates: Open Documentation"
description = "Open the documentation for the crate under the cursor on docs.rs"

[[commands]]
name = "crates-zed.open_repository"
title = "Crates: Open Repository"
description = "Open the repository for the crate under the cursor on crates.io"

[[commands]]
name = "crates-zed.clear_cache"
title = "Crates: Clear Cache"
description = "Clear the local cache of crate information"
