id = "crates-autocomplete"
name = "Crates Autocomplete"
description = "Provides intelligent autocomplete, versioning, and features for Rust crates in Cargo.toml files using crates-lsp"
version = "0.1.1"
schema_version = 1
authors = ["Radu <radu@example.com>"]
repository = "https://github.com/yourusername/crates-autocomplete"

[language_servers.crates-lsp]
name = "crates-lsp"
language = "TOML"
